# Generated by Django 5.2.13 on 2026-04-25 20:37

import random
import string

from django.db import migrations, models


def _generate_codes(apps, schema_editor):
    Agent = apps.get_model("homes", "Agent")
    used = set()
    for agent in Agent.objects.all():
        if agent.agent_code:
            used.add(agent.agent_code)
            continue
        while True:
            letters = "".join(random.choices(string.ascii_uppercase, k=3))
            digits = "".join(random.choices(string.digits, k=3))
            code = f"{letters}-{digits}"
            if code not in used:
                used.add(code)
                break
        agent.agent_code = code
        agent.save()


class Migration(migrations.Migration):

    dependencies = [
        ('homes', '0001_initial'),
    ]

    operations = [
        # 1. Add field without unique so existing rows can have blank
        migrations.AddField(
            model_name='agent',
            name='agent_code',
            field=models.CharField(blank=True, max_length=7, default=""),
            preserve_default=False,
        ),
        # 2. Fill existing rows with generated codes
        migrations.RunPython(_generate_codes, migrations.RunPython.noop),
        # 3. Now enforce unique
        migrations.AlterField(
            model_name='agent',
            name='agent_code',
            field=models.CharField(blank=True, max_length=7, unique=True),
        ),
    ]
