# Generated by Django 5.2.13 on 2026-04-26 21:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homes', '0002_agent_agent_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveChatThread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_ip', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='live_chat_threads', to='homes.agent')),
                ('property', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='live_chat_threads', to='homes.property')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='LiveChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.CharField(choices=[('user', 'User'), ('agent', 'Agent')], max_length=10)),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('thread', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='homes.livechatthread')),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.AddConstraint(
            model_name='livechatthread',
            constraint=models.UniqueConstraint(fields=('property', 'user_ip'), name='unique_live_thread_per_property_user_ip'),
        ),
    ]
