# Generated by Django 5.2.13 on 2026-05-13 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homes', '0003_livechatthread_livechatmessage_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('country', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=40)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('paid', 'Paid (Activated)')], default='pending', max_length=20)),
                ('rejection_reason', models.TextField(blank=True)),
                ('payment_token', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
