# Generated by Django 5.2.13 on 2026-05-13 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homes', '0004_agent_application'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentapplication',
            name='paystack_reference',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
