# Generated by Django 5.2.13 on 2026-05-13 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homes', '0005_add_paystack_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='approval_status',
            field=models.CharField(choices=[('approved', 'Approved'), ('pending_approval', 'Pending Approval'), ('rejected', 'Rejected')], default='approved', max_length=20),
        ),
    ]
